--create database imobiliaria;
CREATE TABLE ENDERECO(
	ID_ENDERECO SERIAL PRIMARY KEY,
    RUA VARCHAR(255),
    NUMERO NUMERIC (10),
    ANDAR NUMERIC (10),
    BLOCO VARCHAR(10),
	BAIRRO VARCHAR(14),
    CIDADE VARCHAR(255),
    UF VARCHAR(2),
    CEP VARCHAR(10)
	
);
CREATE TABLE CLIENTE(
	ID_CLIENTE SERIAL PRIMARY KEY,
	ID_ENDERECO INT NOT NULL,
    NOME_CLIENTE VARCHAR(55) NOT NULL,
    DATA_NASC DATE,
	TELEFONE NUMERIC(11),
	EMAIL VARCHAR(100),
	CPF NUMERIC(14),
	RG  VARCHAR(10),
	ESTADO_CIVIL VARCHAR(12),
	PROFISSAO VARCHAR(100),
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE VENDEDOR(
	ID_VENDEDOR SERIAL PRIMARY KEY,
    NOME VARCHAR(55) NOT NULL, 
    ID_ENDERECO INT NOT NULL,
    DATA_NASC DATE,
    ENDERECO VARCHAR(100),
    TELEFONE NUMERIC(11),
    EMAIL VARCHAR(100),
    CPF NUMERIC(14),
    RG  VARCHAR(10),
    ESTADO_CIVIL VARCHAR(12),
    CARGO VARCHAR(100),
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE PROPRIETARIO(
	ID_PROPRIETARIO SERIAL PRIMARY KEY,
    ID_ENDERECO INT NOT NULL,
    NOME VARCHAR(55) NOT NULL, 
    DATA_NASC DATE,
    TELEFONE NUMERIC(11),
    EMAIL VARCHAR(100),
    CPF NUMERIC(14),
    RG  VARCHAR(10),
    ESTADO_CIVIL VARCHAR(12),
	PROFISSAO VARCHAR(100),
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO)
	
);
CREATE TABLE TIPO_IMOVEL(
	ID_TIPO SERIAL PRIMARY KEY,
    CASA BOOLEAN,
    APARTAMENTO BOOLEAN,
    KITNET BOOLEAN
    
);
CREATE TABLE IMOVEL(
	ID_IMOVEL SERIAL PRIMARY KEY,
	ID_TIPO INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    ID_PROPRIETARIO INT NOT NULL,
    VALOR_LUZ VARCHAR(100),
    VALOR_AGUA VARCHAR(100),
    CONDOMINIO VARCHAR(100),
    PRECO_TOTAL VARCHAR(100),
    PROPAGANDA VARCHAR(100),
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO),
	FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO),
	FOREIGN KEY (ID_TIPO) REFERENCES TIPO_IMOVEL(ID_TIPO)
		
);

CREATE TABLE BANCO (
	ID_BANCO NUMERIC PRIMARY KEY,
    NOME_BANCO VARCHAR (255)

);

CREATE TABLE IMOBILIARIA (
	ID_IMOBILIARIA SERIAL PRIMARY KEY,
	ID_BANCO INT,
	ID_VENDEDOR INT,
	ID_CLIENTE INT,
	ID_PROPRIETARIO INT,
	FOREIGN KEY (ID_BANCO) REFERENCES BANCO(ID_BANCO),
	FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID_PROPRIETARIO)
);

